"""Generate the canonical TSV schema include used by Sphinx docs.

This script keeps documentation in sync with the code-level schema constants in
`src/dbs_annotator/config.py`.
"""

from __future__ import annotations

from pathlib import Path

from dbs_annotator.config import ANNOTATION_TSV_COLUMNS, TSV_COLUMNS

OUTPUT_FILE = Path("docs/_generated/tsv_schema.inc.rst")

SESSION_META: dict[str, tuple[str, str]] = {
    "date": ("string", "Date of the entry (``YYYY-MM-DD``)."),
    "time": ("string", "Time of the entry (``HH:MM:SS``)."),
    "timezone": ("string", "Timezone abbreviation/offset at capture time."),
    "block_id": ("integer", "Index of the stimulation block within a session."),
    "session_ID": ("integer", "Internal session counter."),
    "is_initial": (
        "integer",
        "``1`` for baseline Step 1 entries; ``0`` for Step 3 session entries.",
    ),
    "scale_name": ("string", "Clinical scale name (or newline-separated names)."),
    "scale_value": ("string/float", "Scale value (``NaN`` when not assessed)."),
    "electrode_model": ("string", "Selected electrode model name."),
    "program_ID": ("string", "Stimulation program label (e.g., ``A``, ``B``)."),
    "left_stim_freq": ("float", "Left stimulation frequency (Hz)."),
    "left_anode": ("string", "Left anode contact(s)."),
    "left_cathode": ("string", "Left cathode contact(s)."),
    "left_amplitude": ("float", "Left total amplitude (mA)."),
    "left_pulse_width": ("float", "Left pulse width (µs)."),
    "right_stim_freq": ("float", "Right stimulation frequency (Hz)."),
    "right_anode": ("string", "Right anode contact(s)."),
    "right_cathode": ("string", "Right cathode contact(s)."),
    "right_amplitude": ("float", "Right total amplitude (mA)."),
    "right_pulse_width": ("float", "Right pulse width (µs)."),
    "notes": ("string", "Free-text note for this entry."),
}

ANNOTATION_META: dict[str, tuple[str, str]] = {
    "date": ("string", "Date of the entry (``YYYY-MM-DD``)."),
    "time": ("string", "Time of the entry (``HH:MM:SS``)."),
    "timezone": ("string", "Timezone abbreviation/offset at capture time."),
    "annotation": ("string", "Free-text annotation."),
}


def _render_table(
    title: str,
    columns: list[str],
    meta: dict[str, tuple[str, str]],
) -> str:
    lines = [
        title,
        "^" * len(title),
        "",
        ".. list-table::",
        "   :widths: 25 15 60",
        "   :header-rows: 1",
        "",
        "   * - Column",
        "     - Type",
        "     - Description",
    ]
    for column in columns:
        col_type, description = meta[column]
        lines.extend(
            [
                f"   * - ``{column}``",
                f"     - {col_type}",
                f"     - {description}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def build_rst() -> str:
    if set(TSV_COLUMNS) != set(SESSION_META):
        missing = set(TSV_COLUMNS).difference(SESSION_META)
        extra = set(SESSION_META).difference(TSV_COLUMNS)
        raise ValueError(
            "SESSION_META keys do not match TSV_COLUMNS. "
            f"Missing={sorted(missing)}, extra={sorted(extra)}"
        )

    if set(ANNOTATION_TSV_COLUMNS) != set(ANNOTATION_META):
        missing = set(ANNOTATION_TSV_COLUMNS).difference(ANNOTATION_META)
        extra = set(ANNOTATION_META).difference(ANNOTATION_TSV_COLUMNS)
        raise ValueError(
            "ANNOTATION_META keys do not match ANNOTATION_TSV_COLUMNS. "
            f"Missing={sorted(missing)}, extra={sorted(extra)}"
        )

    parts = [
        "..",
        "   Auto-generated by scripts/generate_tsv_schema_docs.py.",
        "   Do not edit manually; regenerate from code constants.",
        "",
        _render_table(
            "Programming session TSV columns",
            list(TSV_COLUMNS),
            SESSION_META,
        ),
        _render_table(
            "Annotations-only TSV columns",
            list(ANNOTATION_TSV_COLUMNS),
            ANNOTATION_META,
        ),
    ]
    return "\n".join(parts)


def main(*, check: bool = False) -> int:
    rendered = build_rst()
    if check:
        if not OUTPUT_FILE.exists():
            print(f"[schema-docs] Missing generated file: {OUTPUT_FILE}")
            return 1
        existing = OUTPUT_FILE.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                "[schema-docs] Generated TSV schema docs are out of date. "
                "Run `uv run python scripts/generate_tsv_schema_docs.py`."
            )
            return 1
        print("[schema-docs] TSV schema docs are up to date.")
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(rendered, encoding="utf-8")
    print(f"[schema-docs] Wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Generate docs/_generated/tsv_schema.inc.rst from code schema constants."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated output is stale or missing.",
    )
    args = parser.parse_args()
    raise SystemExit(main(check=args.check))
