from __future__ import annotations

import os
from datetime import datetime
from importlib import metadata

# Force a non-interactive matplotlib backend before any autodoc import. Several
# modules (e.g. dbs_annotator.utils.report_chart_utils) import pyplot at module
# level; on headless CI / RTD runners the default backend would try to open a
# display and either fail or emit warnings that break `-W` builds.
os.environ.setdefault("MPLBACKEND", "Agg")

# Ensure any Qt import during autodoc uses the offscreen platform plugin.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

_DIST_NAME = "dbs-annotator"

project = "DBS Annotator"
author = "Wyss Center"
release = metadata.version(_DIST_NAME)
version = ".".join(release.split(".")[:2])
copyright = f"2025-{datetime.now().year}, {author}"

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "myst_parser",
]

templates_path = ["_templates"]
# Do not list ``_autosummary`` here: those ``.rst`` stubs are generated under
# ``docs/_autosummary/`` during the same build and must be parsed. (Ignore the
# directory in git via ``.gitignore``, not in Sphinx ``exclude_patterns``.)
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Known, non-actionable warnings that would otherwise fail `-W` builds.
# `image.not_readable` covers screenshots under docs/_static/ that are
# regenerated from the running app and not committed to git (tracked in
# the documentation strategy, P3: screenshot pipeline).
suppress_warnings = [
    "image.not_readable",
]

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]

html_theme_options = {
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "style_external_links": True,
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 3,
}

# Autosummary / autodoc behaviour. The project re-exports a handful of classes
# from `dbs_annotator/__init__.py` and each submodule's `__init__.py`. With
# ``members: True`` at module level, the same class is documented on the
# package page *and* on the leaf-module page, triggering "duplicate object"
# warnings. A custom ``_templates/autosummary/module.rst`` keeps the module
# pages as navigation indexes only (no inline members); classes and functions
# still receive full pages via the recursive stub generation.
autosummary_generate = True
autosummary_imported_members = False

autodoc_default_options = {
    # `members` is intentionally False so that `.. automodule::` directives
    # in module stubs do NOT inline every class/function (which would
    # duplicate the dedicated class/function pages generated by the
    # recursive autosummary). Class and function templates explicitly opt
    # back into members / inherited-members.
    "members": False,
    "undoc-members": False,
    "show-inheritance": True,
    "inherited-members": False,
}
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented_params"

# MyST: allow Markdown source alongside reStructuredText. ``linkify`` is
# intentionally NOT enabled because it requires the optional ``linkify-it-py``
# dependency; add explicit links instead of relying on autolinking.
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "smartquotes",
]
myst_heading_anchors = 3

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/docs", None),
}

# `linkcheck` tuning: aggressive timeout, retry transient failures, and ignore
# anchor-only link failures on sites that rewrite fragments (common on GitHub).
linkcheck_timeout = 15
linkcheck_retries = 2
linkcheck_anchors = False
linkcheck_ignore: list[str] = []
